# Generated by Django 5.2.7 on 2025-10-10 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_company_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=32)),
                ('reg_number', models.CharField(db_index=True, help_text='Registration Number', max_length=16)),
                ('make', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('MAINTENANCE', 'Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Current mileage in km')),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], default='PETROL', max_length=20)),
                ('engine_size', models.CharField(blank=True, max_length=20)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='account.company')),
            ],
            options={
                'ordering': ['reg_number'],
                'unique_together': {('org', 'reg_number')},
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.FloatField(blank=True, null=True)),
                ('start_lng', models.FloatField(blank=True, null=True)),
                ('start_address', models.TextField(blank=True)),
                ('end_lat', models.FloatField(blank=True, null=True)),
                ('end_lng', models.FloatField(blank=True, null=True)),
                ('end_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='fleet_app.vehicle')),
            ],
            options={
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='KeyTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ble_id', models.CharField(help_text='BLE Device ID', max_length=64, unique=True)),
                ('label', models.CharField(help_text='Human readable label', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_rssi', models.SmallIntegerField(blank=True, help_text='Signal strength', null=True)),
                ('last_lat', models.FloatField(blank=True, null=True)),
                ('last_lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_tracker', to='fleet_app.vehicle')),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
