# Generated by Django 5.2.7 on 2025-11-20 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftEndChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_lat', models.FloatField(blank=True, null=True)),
                ('parking_lng', models.FloatField(blank=True, null=True)),
                ('parking_address', models.TextField(blank=True)),
                ('fuel_level_photo', models.ImageField(blank=True, null=True, upload_to='shift_end/fuel/')),
                ('fuel_level_detected', models.FloatField(blank=True, help_text='Detected fuel level percentage (0-100)', null=True)),
                ('fuel_level_manual', models.FloatField(blank=True, help_text='Manual fuel level entry if ML fails', null=True)),
                ('photo_front', models.ImageField(blank=True, null=True, upload_to='shift_end/condition/')),
                ('photo_back', models.ImageField(blank=True, null=True, upload_to='shift_end/condition/')),
                ('photo_left', models.ImageField(blank=True, null=True, upload_to='shift_end/condition/')),
                ('photo_right', models.ImageField(blank=True, null=True, upload_to='shift_end/condition/')),
                ('scratches_noted', models.BooleanField(default=False)),
                ('damage_description', models.TextField(blank=True, help_text='Description of any damage or scratches found')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completed_checklists', to=settings.AUTH_USER_MODEL)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='end_checklist', to='fleet_app.shift')),
            ],
            options={
                'verbose_name': 'Shift End Checklist',
                'verbose_name_plural': 'Shift End Checklists',
                'ordering': ['-completed_at'],
            },
        ),
    ]
