# Generated by Django 5.2.6 on 2025-12-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0002_shiftendchecklist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShiftEndChecklist',
        ),
    ]
