# Generated by Django 5.2.7 on 2025-10-10 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('START', 'Start of Shift'), ('END', 'End of Shift')], max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('PASS', 'Pass'), ('FAIL', 'Fail'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=50)),
                ('temperature', models.FloatField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspections', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='fleet_app.shift')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('shift', 'type')},
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('LEFT', 'Left Side'), ('RIGHT', 'Right Side'), ('ROOF', 'Roof'), ('INTERIOR', 'Interior'), ('DASHBOARD', 'Dashboard'), ('ODOMETER', 'Odometer'), ('WINDSHIELD', 'Windshield'), ('TYRES', 'Tyres'), ('LIGHTS', 'Lights'), ('ENGINE', 'Engine'), ('BRAKES', 'Brakes'), ('FUEL', 'Fuel'), ('OTHER', 'Other')], max_length=24)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('N/A', 'Not Applicable'), ('SKIP', 'Skipped')], default='PASS', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspection')),
            ],
            options={
                'ordering': ['part'],
                'unique_together': {('inspection', 'part')},
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('LEFT', 'Left Side'), ('RIGHT', 'Right Side'), ('ROOF', 'Roof'), ('INTERIOR', 'Interior'), ('DASHBOARD', 'Dashboard'), ('ODOMETER', 'Odometer'), ('WINDSHIELD', 'Windshield'), ('TYRES', 'Tyres'), ('LIGHTS', 'Lights'), ('ENGINE', 'Engine'), ('BRAKES', 'Brakes'), ('FUEL', 'Fuel'), ('OTHER', 'Other')], max_length=24)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspections.inspectiontemplate')),
            ],
            options={
                'ordering': ['order', 'part'],
                'unique_together': {('template', 'part')},
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(choices=[('FRONT', 'Front'), ('REAR', 'Rear'), ('LEFT', 'Left Side'), ('RIGHT', 'Right Side'), ('ROOF', 'Roof'), ('INTERIOR', 'Interior'), ('DASHBOARD', 'Dashboard'), ('ODOMETER', 'Odometer'), ('WINDSHIELD', 'Windshield'), ('TYRES', 'Tyres'), ('LIGHTS', 'Lights'), ('ENGINE', 'Engine'), ('BRAKES', 'Brakes'), ('FUEL', 'Fuel'), ('OTHER', 'Other')], max_length=24)),
                ('angle', models.CharField(choices=[('WIDE', 'Wide Shot'), ('CLOSEUP', 'Close-up'), ('PANEL', 'Panel Detail'), ('TYRE', 'Tyre Detail'), ('DAMAGE', 'Damage'), ('GENERAL', 'General')], default='GENERAL', max_length=16)),
                ('file_key', models.CharField(help_text='S3 file key', max_length=255)),
                ('file_url', models.URLField(blank=True, help_text='Public URL for the photo')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(default='image/jpeg', max_length=50)),
                ('taken_at', models.DateTimeField()),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('camera_make', models.CharField(blank=True, max_length=50)),
                ('camera_model', models.CharField(blank=True, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='inspections.inspection')),
                ('inspection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='inspections.inspectionitem')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-taken_at'],
                'indexes': [models.Index(fields=['inspection', 'part'], name='inspections_inspect_904f5d_idx'), models.Index(fields=['taken_at'], name='inspections_taken_a_0bc6c2_idx')],
            },
        ),
    ]
