version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fleet
      POSTGRES_USER: fleet
      POSTGRES_PASSWORD: fleet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  create-bucket:
    image: quay.io/minio/mc:RELEASE.2024-05-10T02-30-40Z
    depends_on:
      - minio
    entrypoint: ["/bin/sh","-c"]
    command: >
      "mc alias set local http://minio:9000 minioadmin minioadmin &&
       mc mb -p local/fleet-photos || true &&
       mc anonymous set download local/fleet-photos || true"

volumes:
  postgres_data:
  minio_data:

