# Generated by Django 5.2.7 on 2025-10-10 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly company identifier', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Company description', null=True)),
                ('email', models.EmailField(help_text='Primary company email', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Company phone number', max_length=20, null=True)),
                ('website', models.URLField(blank=True, help_text='Company website', null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#f1f5f9', help_text='Secondary brand color (hex)', max_length=7)),
                ('max_users', models.PositiveIntegerField(default=50, help_text='Maximum number of users')),
                ('max_vehicles', models.PositiveIntegerField(default=100, help_text='Maximum number of vehicles')),
                ('subscription_plan', models.CharField(choices=[('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', help_text='Subscription plan', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the company is active')),
                ('trial_ends_at', models.DateTimeField(blank=True, help_text='Trial period end date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'account_company',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.company'),
        ),
    ]
