# Generated by Django 5.2.7 on 2025-10-11 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='billing_address',
            field=models.TextField(blank=True, help_text='Billing address', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='billing_email',
            field=models.EmailField(blank=True, help_text='Billing contact email', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_payment_overdue',
            field=models.BooleanField(default=False, help_text='Whether payment is overdue'),
        ),
        migrations.AddField(
            model_name='company',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit Card'), ('bank', 'Bank Transfer'), ('invoice', 'Invoice')], help_text='Payment method', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_ends_at',
            field=models.DateTimeField(blank=True, help_text='Subscription end date', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, help_text='Paid subscription start date', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Trial start date'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='trial', help_text='Subscription plan', max_length=20),
        ),
    ]
