# Generated by Django 5.2.7 on 2025-11-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_company_billing_address_company_billing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payment_customer_id',
            field=models.CharField(blank=True, help_text='Customer ID from payment provider (Stripe, Payfast, etc.)', max_length=200, null=True),
        ),
    ]
