# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_company_payment_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='trial_used',
            field=models.BooleanField(default=False, help_text='Whether company has used its one trial period (no re-trial allowed)'),
        ),
    ]
