# Generated by Django 5.2.7 on 2025-11-13 21:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_company_payment_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal plan code (e.g., 'basic', 'pro')", max_length=50, unique=True)),
                ('display_name', models.CharField(help_text="Display name (e.g., 'Basic Plan')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Price amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', help_text='Billing interval', max_length=10)),
                ('features', models.JSONField(default=dict, help_text="Plan features (e.g., {'max_vehicles': 50, 'max_users': 10})")),
                ('provider_price_id', models.CharField(blank=True, help_text='Price/Plan ID from payment provider (Stripe, Payfast, etc.)', max_length=200, null=True)),
                ('provider', models.CharField(default='stripe', help_text='Payment provider name (stripe, payfast, paystack, yoco, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('unpaid', 'Unpaid')], default='trialing', help_text='Current subscription status', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10)),
                ('current_period_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Start of current billing period')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period')),
                ('trial_end', models.DateTimeField(blank=True, help_text='Trial period end date', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Whether subscription will cancel at period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When subscription was canceled', null=True)),
                ('provider_subscription_id', models.CharField(blank=True, help_text='Subscription ID from payment provider', max_length=200, null=True, unique=True)),
                ('provider_customer_id', models.CharField(blank=True, help_text='Customer ID from payment provider', max_length=200, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata from payment provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(help_text='Company this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing_subscription', to='account.company')),
                ('plan', models.ForeignKey(help_text='Subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(help_text='Payment provider name', max_length=50)),
                ('event_id', models.CharField(help_text='Unique event ID from payment provider', max_length=200, unique=True)),
                ('event_type', models.CharField(help_text="Event type (e.g., 'checkout.session.completed', 'invoice.paid')", max_length=100)),
                ('processed', models.BooleanField(default=False, help_text='Whether this event has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When event was processed', null=True)),
                ('payload', models.JSONField(default=dict, help_text='Raw webhook payload')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of times processing was retried')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Event',
                'verbose_name_plural': 'Webhook Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'event_id'], name='billing_web_provide_1e7620_idx'), models.Index(fields=['processed', '-created_at'], name='billing_web_process_0311f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('provider', models.CharField(default='stripe', help_text='Payment provider name', max_length=50)),
                ('provider_charge_id', models.CharField(blank=True, help_text='Charge/Transaction ID from payment provider', max_length=200, null=True, unique=True)),
                ('provider_invoice_id', models.CharField(blank=True, help_text='Invoice ID from payment provider', max_length=200, null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Raw webhook payload from payment provider')),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='account.company')),
                ('subscription', models.ForeignKey(help_text='Subscription this payment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.companysubscription')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='billing_pay_subscri_d33e55_idx'), models.Index(fields=['company', '-created_at'], name='billing_pay_company_bd73a7_idx'), models.Index(fields=['status', '-created_at'], name='billing_pay_status_bc3ae3_idx')],
            },
        ),
    ]
